# Site settings
title: DanspilS
description: 'Information Security (InfoSec) Architect'
url: 'https://daniel.spilsbury.io'
baseurl: ''
google_analytics: 'UA-86230134-1'
disqus_shortname: 'danspils'

author:
  name: 'DanspilS'
  email: security@spilsbury.io
  twitter_username: danspils
  github_username:  dmspils
  linkedin_username:  danielspilsbury

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:categories/:year/:month/:day/:title:output_ext
# permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'humans.txt', 'LICENSE', 'execute.sh']
