version: 0.1
   
phases:
  install:
    commands:
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist bundler
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
      - aws s3 sync _site/ s3://daniel.spilsbury.io
      - aws cloudfront create-invalidation --distribution-id E3Q6XNPSG9BAQ9  --paths "/*"
      - aws s3 cp robots.txt s3://daniel.spilsbury.io/robots.txt
      - aws s3 cp security.txt s3://daniel.spilsbury.io/.well-known/security.txt